name: Release
on:
  push:
    branches:
      - master
jobs:
  check-next-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    outputs:
      next_version: ${{ steps.versionCheck.outputs.next_version }}
      current_version: ${{ steps.versionCheck.outputs.current_version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - id: versionCheck
        run: |
          echo "next_version=$(node ./bin/happy-next-version.cjs)" >> $GITHUB_OUTPUT
          echo "current_version=$(node ./bin/happy-current-version.cjs)" >> $GITHUB_OUTPUT

  publish: 
    runs-on: ubuntu-latest
    needs: [check-next-version]
    if: ${{ needs.check-next-version.outputs.next_version != '' }}

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Set version
        run: npm version ${{ needs.check-next-version.outputs.next_version }} --no-git-tag-version

      - name: Compile packages
        run: npm run compile

      - name: Run tests
        run: npm run test

      - name: Pushes Git tag
        run: |
          git tag --force v${{ needs.check-next-version.outputs.next_version }} ${GITHUB_SHA}
          git push origin --tags

      - name: Set .npmrc for publish
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ./.npmrc

      - name: Publish packages
        run: npm publish

  create-release:
    runs-on: ubuntu-latest
    needs: [publish, check-next-version]

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - run: node ./bin/happy-release-notes.cjs > ./RELEASE_NOTES.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-next-version.outputs.next_version }}
          release_name: v${{ needs.check-next-version.outputs.next_version }}
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false